---
title: "rmd"
author: "Hexiang Liu"
date: "4/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height=4, fig.width=6, warning = F)
if (!require("pacman")) install.packages("pacman")
pacman::p_load(randomForest, tree, ISLR, rpart, rattle, pROC, partykit, ggplot2, glmnet, leaps, dplyr, keras, neuralnet, imager, ranger,haven,labelled)
```

```{r}
fragile_families<-read_dta('FF_allwaves_2020v2.dta')
```

```{r}
selected2<-c('idnum','k6d1a','k6d1b','k6d1c','k6d1d','k6d1e','k6d1f','k6d1g','k6d1h',
              'k6d1i','k6d1j','k6d1k','k6d1l')
twelve_cols<-fragile_families[,selected2]
twelve_cols1 <- twelve_cols %>% filter_at(colnames(twelve_cols), all_vars(. >= 0))#drop negative values
twelve_cols1$idnum<-as.character(twelve_cols1$idnum)
twelve_cols1[,c(2:13)]<-twelve_cols1[,c(2:13)]-1
twelve_cols1$wellbeing<-rowSums(twelve_cols1[,c(2:13)])
final_y<-twelve_cols1[,c(1,14)]
final_y_100<-final_y%>%mutate(wellbeing=round(4.16*wellbeing))
```

```{r}
#write.csv(final_y,"final_y.csv", row.names = FALSE)
#write.csv(final_y_100,"final_y_100.csv", row.names = FALSE)
```

